### ISSUE TITLE
Could not find json-2.3.1 in any of the sources

### ISSUE THREAD

**Issue by joekndy** [Hi-Rez/Template#1]
getting this error when running `bundle install`

`An error occurred while installing json (2.5.1), and Bundler cannot continue. Make sure that gem install json -v '2.5.1' --source 'https://rubygems.org/' succeeds before bundling.`

**Comment by rezaali** [comment]
Thanks for letting me know @joekndy, can you try: xcode-select --install or bundle update && bundle install.
